Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: nhlgameupdatelambda.NhlGameUpdateLambda
      CodeUri: /Users/Austin_Egri/Documents/Coding_Projects/NhlGameUpdateLambda/app
      Runtime: java8.al2
      Architectures:
        - x86_64