/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nhlgameupdatelambda;

import com.amazonaws.services.lambda.runtime.ClientContext;
import com.amazonaws.services.lambda.runtime.CognitoIdentity;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;
import com.google.common.collect.ImmutableMap;
import nhlgameupdatelambda.testHelpers.TestContext;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.util.Map;

import static org.junit.Assert.*;

public class NhlGameUpdateLambdaTest {

    private Map<String, String> event;
    private Context context;

    private NhlGameUpdateLambda underTest;

    private String expectedResponse;
    private String actualResponse;

    @Before
    public void setup() {
        context = new TestContext();
        underTest = new NhlGameUpdateLambda();
    }

    @After
    public void tearDown() {
        event = null;
        context = null;
        expectedResponse = null;
        actualResponse = null;
    }
    @Test
    public void handleRequest_sampleInput_responseNonNull() {
        setupEventWithGameId();

        whenHandleRequestIsCalled();
        assertNotNull("Response is not null", actualResponse);
    }

    private void whenHandleRequestIsCalled() {
        actualResponse = underTest.handleRequest(event, context);
    }

    private void setupEventWithGameId() {
        event = ImmutableMap.of("GameId", "1111");
    }
}
